#%RAML 1.0
---

title: Transit Movement
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/customs:
  /transit-movement:
      /transits:
        post:
          displayName: Submit details of transit movements
          description: This endpoint takes a JSON body containing the details of transit movements
          is: [headers.acceptHeader]
          securedBy: [sec.x-application]
          body:
            application/json:
              type: !include schemas/submit-transits-request.json
              example: !include examples/submit-transits-request-example.json
          responses:
           204:
